### PR TITLE
✨ Add template-based addon handling to prevent premature processing

### LINKED ISSUE #1181: A lot of error message in the addon manager when there is new template type addon enabled
**Describe the bug**

After the ocm is installed, install the managed serviceaccount addon with template mode:

```
helm install \
            -n open-cluster-management-addon --create-namespace \
            managed-serviceaccount charts/managed-serviceaccount/ \
            --set tag=latest \
            --set featureGates.ephemeralIdentity=true \
            --set hubDeployMode=AddOnTemplate \
            --set targetCluster=cluster1
```

Check the logs of the cluster-manager-addon-manager:

```
I0911 03:40:14.794432       1 controller.go:175] "Starting an addon manager for addon" addonName="managed-serviceaccount"
I0911 03:40:14.794526       1 template_agent.go:283] "Addon template config in addon status is empty" addonName="managed-serviceaccount"
E0911 03:40:14.794547       1 template_agent.go:160] "Unhandled Error" err="GetAgentAddonOptions addon managed-serviceaccount template is nil"
I0911 03:40:14.799079       1 template_agent.go:283] "Addon template config in addon status is empty" addonName="managed-serviceaccount"
E0911 03:40:14.799097       1 template_agent.go:160] "Unhandled Error" err="GetAgentAddonOptions addon managed-serviceaccount template is nil"
I0911 03:40:14.800326       1 template_agent.go:283] "Addon template config in addon status is empty" addonName="managed-serviceaccount"
E0911 03:40:14.800359       1 template_agent.go:160] "Unhandled Error" err="GetAgentAddonOptions addon managed-serviceaccount template is nil"
I0911 03:40:14.800975       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
E0911 03:40:14.801029       1 base_controller.go:277] "Unhandled Error" err="\"addon-configuration-controller\" controller failed to sync \"managed-serviceaccount\", err: placement.cluster.open-cluster-management.io \"global\" not found"
I0911 03:40:14.801769       1 template_agent.go:289] "Addon template spec hash is empty" addonName="managed-serviceaccount"
E0911 03:40:14.801805       1 template_agent.go:156] "Unhandled Error" err="GetAgentAddonOptions failed to get addon managed-serviceaccount template: addon managed-serviceaccount template desired spec hash is empty"
I0911 03:40:14.803220       1 base_controller.go:34] Waiting for caches to sync for CSRSignController
I0911 03:40:14.803235       1 base_controller.go:34] Waiting for caches to sync for addon-deploy-controller
I0911 03:40:14.803240       1 base_controller.go:34] Waiting for caches to sync for CSRApprovingController
I0911 03:40:14.803248       1 base_controller.go:34] Waiting for caches to sync for management-addon-config-controller
I0911 03:40:14.803220       1 base_controller.go:34] Waiting for caches to sync for cma-managed-by-controller
I0911 03:40:14.803260       1 base_controller.go:40] Caches are synced for cma-managed-by-controller
I0911 03:40:14.803262       1 base_controller.go:34] Waiting for caches to sync for addon-config-controller
I0911 03:40:14.803265       1 base_controller.go:78] Starting #1 worker of cma-managed-by-controller controller ...
I0911 03:40:14.803250       1 base_controller.go:34] Waiting for caches to sync for addon-registration-controller
E0911 03:40:14.808562       1 base_controller.go:277] "Unhandled Error" err="\"addon-configuration-controller\" controller failed to sync \"managed-serviceaccount\", err: placement.cluster.open-cluster-management.io \"global\" not found"
E0911 03:40:14.819946       1 base_controller.go:277] "Unhandled Error" err="\"addon-configuration-controller\" controller failed to sync \"managed-serviceaccount\", err: placement.cluster.open-cluster-management.io \"global\" not found"
E0911 03:40:14.841309       1 base_controller.go:277] "Unhandled Error" err="\"addon-configuration-controller\" controller failed to sync \"managed-serviceaccount\", err: placement.cluster.open-cluster-management.io \"global\" not found"
I0911 03:40:14.871330       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:14.880709       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
E0911 03:40:14.883924       1 base_controller.go:277] "Unhandled Error" err="\"addon-configuration-controller\" controller failed to sync \"managed-serviceaccount\", err: Operation cannot be fulfilled on clustermanagementaddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
E0911 03:40:14.897340       1 base_controller.go:277] "Unhandled Error" err="\"addon-configuration-controller\" controller failed to sync \"managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:14.897485       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:14.904039       1 base_controller.go:40] Caches are synced for management-addon-config-controller
I0911 03:40:14.904065       1 base_controller.go:78] Starting #1 worker of management-addon-config-controller controller ...
I0911 03:40:14.904070       1 base_controller.go:40] Caches are synced for addon-registration-controller
I0911 03:40:14.904081       1 base_controller.go:40] Caches are synced for CSRSignController
I0911 03:40:14.904092       1 base_controller.go:78] Starting #1 worker of addon-registration-controller controller ...
I0911 03:40:14.904096       1 base_controller.go:40] Caches are synced for addon-config-controller
I0911 03:40:14.904124       1 base_controller.go:40] Caches are synced for addon-deploy-controller
I0911 03:40:14.904151       1 base_controller.go:78] Starting #1 worker of addon-deploy-controller controller ...
I0911 03:40:14.904170       1 base_controller.go:78] Starting #1 worker of addon-config-controller controller ...
I0911 03:40:14.904099       1 base_controller.go:78] Starting #1 worker of CSRSignController controller ...
I0911 03:40:14.904112       1 base_controller.go:40] Caches are synced for CSRApprovingController
I0911 03:40:14.904195       1 base_controller.go:78] Starting #1 worker of CSRApprovingController controller ...
I0911 03:40:14.904193       1 template_agent.go:289] "Addon template spec hash is empty" addonName="managed-serviceaccount"
E0911 03:40:14.904223       1 template_agent.go:156] "Unhandled Error" err="GetAgentAddonOptions failed to get addon managed-serviceaccount template: addon managed-serviceaccount template desired spec hash is empty"
I0911 03:40:14.904967       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:14.909446       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
E0911 03:40:14.910000       1 base_controller.go:154] "Unhandled Error" err="\"addon-registration-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:14.911205       1 template_agent.go:289] "Addon template spec hash is empty" addonName="managed-serviceaccount"
E0911 03:40:14.911244       1 template_agent.go:156] "Unhandled Error" err="GetAgentAddonOptions failed to get addon managed-serviceaccount template: addon managed-serviceaccount template desired spec hash is empty"
I0911 03:40:14.914777       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:14.920048       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
E0911 03:40:14.922172       1 base_controller.go:277] "Unhandled Error" err="\"addon-configuration-controller\" controller failed to sync \"managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
E0911 03:40:14.923228       1 base_controller.go:154] "Unhandled Error" err="\"addon-registration-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:14.924312       1 template_agent.go:289] "Addon template spec hash is empty" addonName="managed-serviceaccount"
I0911 03:40:14.929412       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
E0911 03:40:14.939307       1 base_controller.go:277] "Unhandled Error" err="\"addon-configuration-controller\" controller failed to sync \"managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
E0911 03:40:14.939962       1 base_controller.go:154] "Unhandled Error" err="\"addon-registration-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:14.945734       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:14.957098       1 registration.go:466] "Rolebinding for addon updated" namespace="cluster1" name="open-cluster-management:managed-serviceaccount:clusterrole:agent" clusterName="cluster1" addonName="managed-serviceaccount"
I0911 03:40:14.957202       1 event.go:377] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"open-cluster-management-hub", Name:"cluster-manager-addon-manager-controller", UID:"d0ac0339-a8a3-40e1-af97-d5d449de4c32", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RoleBindingCreated' Created RoleBinding.rbac.authorization.k8s.io/open-cluster-management:managed-serviceaccount:clusterrole:agent -n cluster1 because it was missing
I0911 03:40:14.959221       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
I0911 03:40:14.970823       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:14.975562       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
E0911 03:40:14.979578       1 base_controller.go:154] "Unhandled Error" err="\"addon-registration-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:14.991198       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:14.999916       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
E0911 03:40:15.000391       1 base_controller.go:154] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
E0911 03:40:15.004738       1 base_controller.go:154] "Unhandled Error" err="\"addon-registration-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:15.009858       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
I0911 03:40:15.010590       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:15.012185       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
I0911 03:40:15.014032       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
I0911 03:40:15.077727       1 csr_helpers.go:174] CSR approved
I0911 03:40:15.102233       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:15.113533       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:15.126241       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
E0911 03:40:15.126423       1 base_controller.go:154] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:15.136274       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
I0911 03:40:15.139889       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:15.160447       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
E0911 03:40:15.161024       1 base_controller.go:154] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:15.161909       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:15.163363       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
I0911 03:40:15.190670       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
E0911 03:40:15.194565       1 base_controller.go:154] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:15.194837       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
I0911 03:40:15.197933       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:15.204191       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:15.205657       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
E0911 03:40:15.209180       1 base_controller.go:154] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
I0911 03:40:15.218212       1 controller.go:171] "There already is a manager started for addon, skipping" addonName="managed-serviceaccount"
I0911 03:40:15.219994       1 addon_config.go:56] "Addon deployment config is nil, return an empty string for agent install namespace" addonNamespace="cluster1" addonName="managed-serviceaccount"
E0911 03:40:15.222932       1 base_controller.go:154] "Unhandled Error" err="\"addon-deploy-controller\" controller failed to sync \"cluster1/managed-serviceaccount\", err: Operation cannot be fulfilled on managedclusteraddons.addon.open-cluster-management.io \"managed-serviceaccount\": the object has been modified; please apply your changes to the latest version and try again"
```

**To Reproduce**

**Expected behavior**

No `template desired spec hash is empty` and `template is nil` errors.

**Environment ie: OCM version, Kubernetes version and provider:**

**Additional context**

### PR DESCRIPTION
**Pull request by zhujian7**
## Summary

This PR adds comprehensive template-based addon handling to the addon framework, preventing premature processing errors and providing better control over addon initialization. The implementation evolved through the PR to ensure complete backward compatibility while delivering robust template-based addon support with a flexible configuration API.

### Problem Solved

Template-based addons were experiencing initialization errors because controllers attempted to process them before their configurations were set:
- "template is nil" errors
- "template desired spec hash is empty" errors  
- Unnecessary retries and error logs during startup
- Race conditions between template configuration and addon processing

See [issue #1181](https://github.com/open-cluster-management-io/ocm/issues/1181) for detailed error logs.

### Solution Architecture

**Phase 1: Core Filtering Infrastructure**
- Added `ManagedClusterAddOnFilterFunc` type for flexible addon filtering
- Implemented `FilterTemplateBasedAddOns` and `AllowAllAddOns` filter functions
- Integrated filtering across all addon controllers (deploy, registration, config, certificate)

**Phase 2: Template-Based Processing Control**
- Added `templateBasedAddOn` parameter to control filtering behavior
- Enhanced parameter naming and documentation for clarity
- Implemented controller-specific logic for addon-config-controller

**Phase 3: Flexible Configuration API Design**
- Implemented public `Option` struct with public fields for transparent configuration
- Added `OptionFunc` pattern allowing custom configuration functions
- Unified API through `NewWithOptionFuncs` supporting both struct and functional patterns
- Ensured zero breaking changes for external interface implementations

### Public API

**Fully Backward Compatible**: No breaking changes to any interfaces or existing code.

```go
// Existing usage (completely unchanged)
manager, err := addonmanager.New(config)
manager.AddAgent(myAddon)
manager.Start(ctx)

// Functional pattern with built-in options
manager, err := addonmanager.NewWithOptionFuncs(config, 
    addonmanager.WithTemplateMode(true))

// Struct pattern with public Option
option := &addonmanager.Option{TemplateBasedAddOn: true}
manager, err := addonmanager.NewWithOptionFuncs(config,
    addonmanager.WithOption(option))

// Custom configuration functions
customFunc := func(opt *addonmanager.Option) {
    opt.TemplateBasedAddOn = shouldEnableTemplateMode()
}
manager, err := addonmanager.NewWithOptionFuncs(config, customFunc)
```

### Key Features

- **Template Mode**: Only process addons with proper AddOnTemplate references when enabled
- **Public Option Struct**: Transparent configuration with public `TemplateBasedAddOn` field
- **OptionFunc Pattern**: Supports custom configuration functions for advanced use cases
- **Unified Constructor**: Single `NewWithOptionFuncs` handles all configuration patterns
- **Controller Coordination**: addon-config-controller sets template configs, others wait when needed
- **Comprehensive Documentation**: Clear explanations of behavior and architectural decisions
- **Error Prevention**: Eliminates "template is nil" and "spec hash empty" errors
- **Zero Breaking Changes**: All existing code continues to work unchanged

### Template Processing Flow

1. **addon-config-controller** processes all addons (bypasses filter) to set `specHash` in `status.configReferences`
2. **Other controllers** wait for template references when template mode is enabled
3. **Race conditions eliminated** between template configuration and addon processing
4. **Clean error logs** with meaningful processing flow

### Configuration Flexibility

The API supports multiple configuration patterns:

- **Simple functional**: `WithTemplateMode(true)`
- **Struct-based**: `WithOption(&Option{TemplateBasedAddOn: true})`
- **Custom functions**: User-defined functions that mutate the Option struct
- **Composable**: Multiple OptionFunc functions can be chained together

This design allows external implementers to create their own configuration functions while providing sensible built-in options for common use cases.

### Implementation Highlights

- **Non-breaking Design**: No interface changes, functionality added through constructor options
- **Extensible Pattern**: Public `Option` struct and `OptionFunc` type allow future additions
- **Comprehensive Testing**: Unit tests for all filtering scenarios and configuration patterns
- **Clear Documentation**: Extensive comments explaining design decisions and GitHub issue context
- **Production Ready**: Addresses real-world template addon deployment issues

## Test Plan

- [x] Unit tests for template-based filtering logic
- [x] Integration tests with both filtering modes
- [x] Verification that template errors are eliminated  
- [x] Backward compatibility validation
- [x] Interface compatibility with external implementations
- [x] Configuration pattern validation (struct and functional)
- [x] OptionFunc composition testing

## Related issue(s)

Fixes https://github.com/open-cluster-management-io/ocm/issues/1181

This PR provides a complete solution for template-based addon handling while maintaining absolute backward compatibility through a flexible, extensible configuration system that supports multiple usage patterns.

### CODE REVIEW

File: pkg/utils/addon.go [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+// This is used to selectively process only certain types of addons based on custom criteria.
+type ManagedClusterAddOnFilterFunc func(mca *addonapiv1alpha1.ManagedClusterAddOn) bool
+
+// AllowAllAddOns is a filter function that accepts all ManagedClusterAddOn objects.
+// This function always returns true, making it suitable as a no-op filter when
+// no filtering is desired.
+func AllowAllAddOns(mca *addonapiv1alpha1.ManagedClusterAddOn) bool {
+	return true
+}
+
```
Comment (qiujian16) [inline pkg/utils/addon.go:18]: could we add a a filter for selectedAddons? When addon framework is started, we already know which addons the framework should watch.

File: pkg/addonmanager/controllers/certificate/csrapprove.go [hunk 2]
```diff
@@ -68,6 +70,7 @@ func NewCSRApprovingController(
 	csrBetaInformer v1beta1certificatesinformers.CertificateSigningRequestInformer,
 	addonInformers addoninformerv1alpha1.ManagedClusterAddOnInformer,
 	agentAddons map[string]agent.AgentAddon,
+	mcaFilterFunc utils.ManagedClusterAddOnFilterFunc,
```
Comment (qiujian16) [inline pkg/addonmanager/controllers/certificate/csrapprove.go:73]: the agentAddons has already filtered the addon, does it?

Comment (zhujian7) [reply pkg/addonmanager/controllers/certificate/csrapprove.go:73]: This mcaFilterFunc is for a different purpose, this is to make the addon-manager(in ocm) be able to pass the utils.FilterTemplateBasedAddOns to let controllers(in addon-framework) not process until the mca.Status.ConfigReferences has addontemplate set.
With this, it helps git rid of some unnecessary error logging in the addon-manager. see https://github.com/open-cluster-management-io/ocm/issues/1181

File: pkg/addonmanager/base_manager.go [hunk 3]
```diff
@@ -77,7 +77,14 @@ func (a *BaseAddonManagerImpl) StartWithInformers(ctx context.Context,
...
 	clusterInformers clusterv1informers.SharedInformerFactory,
-	dynamicInformers dynamicinformer.DynamicSharedInformerFactory) error {
+	dynamicInformers dynamicinformer.DynamicSharedInformerFactory,
+	templateBasedAddOn bool,
+) error {
+	// Determine the appropriate filter function based on templateBasedAddOn flag
+	mcaFilterFunc := utils.AllowAllAddOns
+	if templateBasedAddOn {
+		mcaFilterFunc = utils.FilterTemplateBasedAddOns
+	}
```
[the remark this answers is not in the document]
Comment (zhujian7) [reply pkg/addonmanager/base_manager.go]: I think we do not need this change because there is a case it is template based addon, but the `mca.Status.ConfigReferences configRef.Group == "addon.open-cluster-management.io" && configRef.Resource == "addontemplates"` are not set timely, we need to return false and check again

File: pkg/addonmanager/base_manager.go [hunk 4]
```diff
@@ -71,13 +72,32 @@ func (a *BaseAddonManagerImpl) Trigger(clusterName, addonName string) {
...
 	addonInformers addoninformers.SharedInformerFactory,
 	clusterInformers clusterv1informers.SharedInformerFactory,
-	dynamicInformers dynamicinformer.DynamicSharedInformerFactory) error {
+	dynamicInformers dynamicinformer.DynamicSharedInformerFactory,
+) error {
+	// Determine the appropriate filter function based on templateBasedAddOn field
+	mcaFilterFunc := utils.AllowAllAddOns
+	if a.templateBasedAddOn {
+		mcaFilterFunc = utils.FilterTemplateBasedAddOns
+	}
```
[the remark this answers is not in the document]
Comment (zhujian7) [reply pkg/addonmanager/base_manager.go:129]: I think "When templateBasedAddOn is enabled this prevents non-template MCAs from being processed." is ok, because the manager either is a template based, or it is not. It will not manage both template-based and non-template-based addons.

File: pkg/addonmanager/base_manager.go [hunk 5]
```diff
@@ -26,23 +26,48 @@ import (
 	"open-cluster-management.io/sdk-go/pkg/basecontroller/factory"
 )
 
+// Option is a function that configures BaseAddonManagerImpl during construction.
+type Option func(*BaseAddonManagerImpl)
```
Comment (qiujian16) [inline pkg/addonmanager/base_manager.go]: if we go with option func pattern, I think we need an Public Option struct and all its field should be public. We then allows an implementation of the OptionFunc to mutate the option, and pass the option to the manager

Comment (zhujian7) [reply pkg/addonmanager/base_manager.go]: Fixed, PTAL

**Review by qiujian16 — COMMENTED** [review]
/approve
/lgtm
