### PR TITLE
:bug: allow arbitrary config fields when calculating config hash

### LINKED ISSUE #364: spechash remains empty for secrets
**Describe the bug**
https://kubernetes.slack.com/archives/C01GE7YSUUF/p1709566835547519

**To Reproduce**

**Expected behavior**

**Environment ie: OCM version, Kubernetes version and provider:**

**Additional context**

### PR DESCRIPTION
**Pull request by haoqing0110**
Fix https://github.com/open-cluster-management-io/ocm/issues/364 https://github.com/open-cluster-management-io/addon-framework/issues/237

### CODE REVIEW

File: pkg/utils/helpers.go [hunk 1]
```diff
@@ -350,14 +350,15 @@ func IsOwnedByCMA(addon *addonapiv1alpha1.ManagedClusterAddOn) bool {
...
+// GetSpecHash returns the sha256 hash of the spec field or data field of the given object
 func GetSpecHash(obj *unstructured.Unstructured) (string, error) {
 	if obj == nil {
 		return "", fmt.Errorf("object is nil")
 	}
 	spec, ok := obj.Object["spec"]
 	if !ok {
-		return "", fmt.Errorf("object has no spec field")
+		// handle cases like secret and configmaps
+		spec = obj.Object["data"]
```
Comment (qiujian16) [inline pkg/utils/helpers.go]: what if an API that does not have data field and spec field?

Comment (haoqing0110) [reply pkg/utils/helpers.go]: var spec will be nil and return a hash like [case](https://github.com/open-cluster-management-io/addon-framework/pull/243/files#diff-e5c8046fa2e55ccd0b73a7f6cd75cfd2798f8e7bec08210444e01d6ffac0c0f0R91) .For example, if a configmap removed data field, hash will update and trigger an upgrade.

Comment (qiujian16) [reply pkg/utils/helpers.go]: how about we remove status and metadata part and hash?

Comment (haoqing0110) [reply pkg/utils/helpers.go]: Yes, sounds better. Have modified the code.

File: pkg/utils/helpers.go [hunk 2]
```diff
@@ -350,22 +350,25 @@ func IsOwnedByCMA(addon *addonapiv1alpha1.ManagedClusterAddOn) bool {
...
+	delete(obj.Object, "status")
+
+	// the object key will also be included in the hash calculation to ensure that different fields with the same value have different hashes
+	configBytes, err := json.Marshal(obj.Object)
 	if err != nil {
 		return "", err
 	}
 
-	hash := sha256.Sum256(specBytes)
+	hash := sha256.Sum256(configBytes)
```
Comment (tamalsaha) [inline pkg/utils/helpers.go:376]: May be a fast non-cryptographic is good enough here?
https://github.com/zeebo/xxh3

File: pkg/utils/helpers.go [hunk 3]
```diff
@@ -350,22 +350,25 @@ func IsOwnedByCMA(addon *addonapiv1alpha1.ManagedClusterAddOn) bool {
...
 		return "", fmt.Errorf("object is nil")
 	}
-	spec, ok := obj.Object["spec"]
-	if !ok {
-		return "", fmt.Errorf("object has no spec field")
-	}
 
-	specBytes, err := json.Marshal(spec)
+	// remove non config related fields, the remaining filed should be spec, data, other use defined fields or even empty
+	delete(obj.Object, "apiVersion")
```
Comment (tamalsaha) [inline pkg/utils/helpers.go]: This will modify the input object. Is that going to cause any unintended issue? May be a better choice is to perform a shallow copy into a new map and use that calculate hash?

```
cp := map[string]any{}
for k, v := range obj.Object {
  switch k: {
    case "apiVersion", "kind", "metadata", "status":
    default:
       cp[k] = v
   }
} 
```

Comment (haoqing0110) [reply pkg/utils/helpers.go]: Thanks for raising this, have modified the code.

File: pkg/utils/helpers.go (hunk 2 above)
Comment (haoqing0110) [reply pkg/utils/helpers.go:376]: This seems to have better performance, but might not be suitable for the addon case, for example, a cluster-scoped config hash will be exposed to cma, mca and work, and might be cracked by an unexpected namespace-level user.
